local_url: 127.0.0.1:3536/
remote_url: primd.net:3536/
fullscreen_toggle: F11
card_file: decks/movement.ron
movement_controls:
  forward: !Key W
  backward: !Key S
  left: !Key A
  right: !Key D
  jump: !Key Space
  crouch: !Key LControl
  sensitivity: 0.001
graphics_settings:
  primary_ray_dist: 100
  transparency_ray_dist: 75
  shadow_ray_dist: 40
  transparent_shadow_ray_dist: 40
  ao_ray_dist: 15
replay_settings:
    replay_folder: replays
    record_replay: false
do_profiling: false
crash_log: crash_log.txt
singleplayer_settings:
    name: "Singleplayer"
    delta_time: 0.03
    is_remote: false
    player_count: 1
    render_size:
      x: 32
      y: 16
      z: 32
    spawn_location: 
      x: 10000.0
      y: 1810.0
      z: 10000.0
    max_loaded_chunks: 8192
    max_worldgen_rate: 256
    max_update_rate: 256
    world_gen: Normal
    fixed_center: false
practice_range_settings:
    name: "Practice Range"
    delta_time: 0.03
    is_remote: false
    player_count: 1
    render_size:
      x: 8
      y: 8
      z: 8
    spawn_location: 
      x: 10000.0
      y: 1810.0
      z: 10000.0
    max_loaded_chunks: 512
    max_worldgen_rate: 512
    max_update_rate: 512
    world_gen: PracticeRange
    fixed_center: true
create_lobby_settings:
    name: "Standard Open Multiplayer"
    delta_time: 0.03
    is_remote: true
    player_count: 2
    render_size:
      x: 32
      y: 16
      z: 32
    spawn_location: 
      x: 10000.0
      y: 1810.0
      z: 10000.0
    max_loaded_chunks: 2048
    max_worldgen_rate: 128
    max_update_rate: 128
    world_gen: Normal
    fixed_center: false