local_url: ws://127.0.0.1:3536/extreme_bevy?next=2
remote_url: ws://primd.net:3536/extreme_bevy?next=2
is_remote: false
player_count: 1
fullscreen_toggle: F11
movement_controls:
  forward: !Key W
  backward: !Key S
  left: !Key A
  right: !Key D
  jump: !Key Space
  crouch: !Key LControl
  sprint: !Key LShift
  sensitivity: 0.001
ability_controls:
- !Mouse Left
- !Mouse Right
- !Key E
graphics_settings:
  primary_ray_dist: 100
  transparency_ray_dist: 75
  shadow_ray_dist: 50
  transparent_shadow_ray_dist: 50
  ao_ray_dist: 40
delta_time: 0.03333333