local_url: ws://127.0.0.1:3536/extreme_bevy?next=
remote_url: ws://primd.net:3536/extreme_bevy?next=
is_remote: false
player_count: 1
fullscreen_toggle: F11
card_file: decks/characters/flying_rocketeer.ron
movement_controls:
  forward: !Key W
  backward: !Key S
  left: !Key A
  right: !Key D
  jump: !Key Space
  crouch: !Key LControl
  sensitivity: 0.001
graphics_settings:
  primary_ray_dist: 100
  transparency_ray_dist: 75
  shadow_ray_dist: 40
  transparent_shadow_ray_dist: 40
  ao_ray_dist: 25
delta_time: 0.03
replay_settings:
    replay_file: replay.txt
    replay_mode: None
do_profiling: false
crash_log: crash_log.txt