local_url: ws://127.0.0.1:3536/extreme_bevy?next=
remote_url: ws://primd.net:3536/extreme_bevy?next=
fullscreen_toggle: F11
card_file: decks/characters/hammer_man.ron
movement_controls:
  forward: !Key W
  backward: !Key S
  left: !Key A
  right: !Key D
  jump: !Key Space
  crouch: !Key LControl
  sensitivity: 0.001
graphics_settings:
  primary_ray_dist: 100
  transparency_ray_dist: 75
  shadow_ray_dist: 40
  transparent_shadow_ray_dist: 40
  ao_ray_dist: 25
replay_settings:
    replay_folder: replays
    record_replay: false
do_profiling: false
crash_log: crash_log.txt
create_lobby_settings:
    name: "Standard Open Multiplayer"
    delta_time: 0.03
    is_remote: true
    player_count: 2
    render_size:
      x: 32
      y: 16
      z: 32
    spawn_location: 
      x: 10000.0
      y: 1810.0
      z: 10000.0
    max_loaded_chunks: 2048
    world_gen: Normal
    fixed_center: false